# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "hansol's 개발 블로그;"
description: > # this means to ignore newlines until "email:"
   작은 변화는 곧 큰 변화를 초래한다.

email: doingnow94@gmail.com
#blog logo
logo: "/assets/images/hs_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'hansol kim'
author: 'hansol kim'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://mentalk94.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/mentalK94
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

category_list: [ OS, Network, Design Pattern ]